### ISSUE TITLE
[ENHANCEMENT] opensearch.opensearchplugin add groupID field to org.opensearch.plugin

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/cross-cluster-replication#534]
### Description

The configuration modification for the gradle plugin `opensearch.pluginzip` to make sure the `groupId` is added as `org.opensearch.plugin` to the publication `pluginZip` inside the `build.gradle` file.

### Related META issue

Part of: https://github.com/opensearch-project/opensearch-build/issues/2521
From solution: https://github.com/opensearch-project/OpenSearch/issues/3692

### Current Behavior

The `opensearch.opensearchplugin` uses the default setting for `groupId` as `org.opensearch.plugin`, this when extended with open source community, it should be feasible to ammend the `groupId` as per required, hence for opensearch plugins the `groupId` should be mentioned as `org.opensearch.plugin` to make sure the opensearch plugins are published to this `groupID` and for other generic uses this can be extended to the custom `groupId`.

### Expected Behavior

Once the `groupId` is added as `org.opensearch.plugin` to the publication `pluginZip` inside the `build.gradle` file, the plugin zips should continue to be published to the existing `groupID`.

### Proposed solution

Solution from the PR: https://github.com/opensearch-project/OpenSearch/issues/3692

**Comment by ankitkala** [comment]
Should be a minor fix. We'll pick this up before 2.4 release.

**Comment by ankitkala** [comment]
@prudhvigodithi we just need to add a `groupID: org.opensearch.plugin` [here](https://github.com/opensearch-project/cross-cluster-replication/blob/main/build.gradle#L176) right? 
We don't need to change `project.group` [here](https://github.com/opensearch-project/cross-cluster-replication/blob/main/build.gradle#L93)? Asking just for confirmation due to [this](https://github.com/opensearch-project/OpenSearch/issues/3692#issuecomment-1207762074). 

Also, anything to verify/test here?

FYI: @sricharanvuppu will be working on this.
