### ISSUE TITLE
[BUG] Replication auto pauses on follower cluster having wait_for_active_shards true

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/cross-cluster-replication#544]
**What is the bug?**

Replication auto pauses on follower indices having `wait_for_active_shards` set to true and replica shards failing 

**How can one reproduce the bug?**
1. create index having wait_for_active_shards set to true and replica count set to 1 on 3 node leader cluster 
2. start replication on 3 node follower cluster
3.  stop one node
4. Verify that replication auto pauses

**What is the expected behavior?**

1. Replication should just wait for active shards 
2. Alternate is that follower cluster doesn't copy over `wait_for_active_shards` index setting .

**Comment by priyatsh** [comment]
Fix description - The leader index setting "wait_for_active_shards" will not be copied/applied on the follower cluster. The default value of said setting will be assumed at the follower cluster unless specified or changed specifically for the follower cluster.

Following will be the expected behaviour in the identified scenarios relating to the "wait_for_active_shards" index setting,

1. If the wait_for_active_shards setting is set to “all” during index creation, the index replication will succeed but the said setting will not be copied to the follower cluster(Verify through the “_settings” API). If one of the follower node goes down, the replication should still continue.

2. If the wait_for_active_shards setting is set to “all” during index creation, and is later changed dynamically to any other valid value, on applying replication again, replication should not be affected and the setting value should also not change on the follower-cluster.

3. If the wait_for_active_shards setting is set to “default/any valid value”, and later changed to “all”, then the setting change should be ignored at the follower-cluster. No change in replication or the said setting's value.
NOTE- In all the above cases, the setting “wait_for_active_shards” value should be “default” on the follower-cluster.

4. If the follower index setting "wait_for_active_shards" is set to valid value in “start-replication” API, then that should be applied to the follower cluster.

5. If the follower index setting "wait_for_active_shards" is set to valid value in “update-settings” API for the follower cluster, then that should be applied on the follower cluster.
