### ISSUE TITLE
[Discuss] Integration of Full Cluster Replication with other plugins

### ISSUE THREAD

**Issue by ankitkala** [opensearch-project/cross-cluster-replication#561]

**Comment by dparker18** [comment]
Is there a recommended way for an ISM policy to trigger cross-cluster replication for an index? 

The use case is having separate clusters for hot and cold data. Because our index names are date-stamped, it probably rules out auto-follow replication rules. With a `replicate` ISM action, we could wait until today's hot data is ready to go cold and the usage pattern moves from write-heavy to read only.

**Comment by mrMigles** [comment]
Hi,

Are there plans to support security plugin entities (users, roles) for cross-cluster-replication? 

https://forum.opensearch.org/t/security-replication-in-disaster-recovery-scheme/13778
